#!/bin/bash

# count how many updates we have got
ups=`/usr/lib/update-notifier/apt-check --human-readable | ack '^(\d+) updates can be applied immediately\.$' --output='$1'`

# print the results
if [ "$ups" -eq "1" ]
then
  echo "There is 1 update"
elif [ "$ups" -gt "1" ]
then
  echo "There are $ups updates"
else
  echo "Up to date"
fi
